### ISSUE TITLE
Hardcoded MRN

### ISSUE THREAD

**Issue by vlad-ignatov** [smart-on-fhir/smart-stub#1]
The launch function should use the `patientId` variable here https://github.com/smart-on-fhir/smart-stub/blob/master/client.html#L38

**Comment by vlad-ignatov** [comment]
What about the actual server? Perhaps it needs restarting?
Also it could be just `"patient": patientId,`

**Comment by nschwertner** [comment]
Updated the server. Then again, this is just an example of app launch with the stub. Nothing should depend on it.

**Comment by vlad-ignatov** [comment]
Thanks. Now that it works I can use it to provide examples of problematic patient records. You can try to
launch `https://fhir.smarthealthit.org/apps/diabetes-monograph/launch.html` with mrn `hca-pat-81`. There are some patients like this (they don't have "identifier" but only "id") in DSTU2 and some apps are not compatible with them. What can we do about that?

**Comment by nschwertner** [comment]
Is this patient-app issue specific to the stub-based launch, or does it occur in other contexts as well (FHIR Starter, etc)?

**Comment by vlad-ignatov** [comment]
I can reproduce it with the fhirstarter and FHIR Demo App. The patient name is Magda Bachmann.

**Comment by nschwertner** [comment]
Ok. Sounds like the problem is within the HCA sample patients generator (unrelated to the stub). I will look into it.

**Comment by vlad-ignatov** [comment]
It seems that those patients (starting with "hca-pat-") do not  exist n DSTU1 which is why the gallery does not have this problem on production. Is uses DSTU1 for the patient selector.

**Comment by nschwertner** [comment]
We should update the gallery to use DSTU2 as the primary authentication and patient enumeration source. It is the current version of SMART that is supported.

**Comment by nschwertner** [comment]
Ok, so I added the identifier codings to the HCA sample patients. However, they still won't work with the diabetes monograph, because their MedicationOrder-s lack `dosageInstruction`, which I believe is mandatory in SMART-on-FHIR (see http://docs.smarthealthit.org/profiles/ which needs to be updated). We will need to investigate this further.

**Comment by p2** [comment]
Why does the diabetes monograph depend on `identifier`?

**Comment by nschwertner** [comment]
Apparently `dosageInstruction` is not mandatory in SMART, so the problem is within Diabetes Monograph (i.e. not much we can do) See https://github.com/smart-on-fhir/hca-fhir-importer/issues/1

**Comment by nschwertner** [comment]
Well, on second thought, I will look into DiabetesMonograph... could be that a tweak or two in the SMART-on-FHIR data layer may resolve the behavior.

**Comment by nschwertner** [comment]
Oh, and the patient `identifier` is mandatory in SMART (see http://docs.smarthealthit.org/profiles/), so it's fair for Diabetes Monograph to assume its existence (not the same as `dosageInstruction`)

**Comment by p2** [comment]
My question was more to learn what they're using it for. :)
